### ISSUE TITLE
Doesn't work with Strapi v4.1.8

### ISSUE THREAD

**Issue by dzcpy** [alexzaganelli/strapi-plugin-email-designer#93]
### Expected behavior

There is a babel error after upgrading Strapi to v4.1.8

### Screenshots

![image](https://user-images.githubusercontent.com/203980/163307982-1a2bdb93-ecb7-40b0-bc14-8556b50b9a8d.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version: 8.x
- Strapi version: 4.1.8
- Plugin version: 2.1.0
- Database: postgresql
- Operating system: windows

**Comment by Flowko** [comment]
@alexzaganelli hi, hope u doing well!
a more detailed error, happens only on latest version of strapi `4.1.8` 
`strapi-plugin-email-designer\\admin\\src\\pages\\HomePage\\index.js:150:10: ERROR: Transforming for-await loops to the configured target environment ("es2015") is not supported yet`

**Comment by mattia-beta** [comment]
I'm on strapi 4.1.8 i've got the same error.

```node_modules/strapi-plugin-email-designer/admin/src/pages/HomePage/index.js:150:10: ERROR: Transforming for-await loops to the configured target environment ("es2015") is not supported yet\n```

**Comment by kashkashio** [comment]
Any news? got the same issue.

**Comment by alexzaganelli** [comment]
Thank you all for your contribution!
This issue should be fixed on 2.1.1
